folders:
  - .devcontainer/devcontainer.json:
      content: |
        {
          "name": "My Dev Container",
          "dockerFile": "Dockerfile",
          "settings": {
            "terminal.integrated.shell.linux": "/bin/bash"
          },
          "extensions": [
            "dbaeumer.vscode-eslint",
            "esbenp.prettier-vscode",
            "ms-azuretools.vscode-docker",
            "ms-kubernetes-tools.vscode-kubernetes-tools",
            "ms-python.python",
            "ms-vscode-remote.remote-containers",
            "redhat.vscode-yaml",
            "visualstudioexptteam.vscodeintellicode"
          ],
          "postCreateCommand": "yarn install"
        }
