structure:
  - .prettierrc:
      content: |
        {
          "singleQuote": true,
          "trailingComma": "es5",
          "tabWidth": 2,
          "semi": false
        }
  - .prettierignore:
      content: |
        node_modules/
        dist/
  - README.md:
      content: |
        # Prettier Configuration
        Standard Prettier configuration for the project.
        ## Usage
        Add the `.prettierrc` and `.prettierignore` files to your project.
