name: generate-terminal-gifs

on:
  push:
    paths:
      - 'docs/vhs/*.tape'

jobs:
  run:
    strategy:
      matrix:
        tapes:
          - 'docs/vhs/install.tape'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - uses: charmbracelet/vhs-action@v1
        with:
          path: ${{ matrix.tapes }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: Update generated VHS GIF
          branch: main
          commit_user_name: vhs-action 📼
          commit_user_email: actions@github.com
          commit_author: vhs-action 📼 <actions@github.com>
          file_pattern: '*.gif'
